### ISSUE TITLE
Failing to run on newly created lib

### ISSUE THREAD

**Issue by andresggarcia** [yohangz/packer-cli#11]
Just followed the readme.
Right after running the install script: 

```bash
> my-lib@1.0.0 watch /Users/agarciag/Documents/Apps/my-lib
> packer watch

node-resolve: setting options.module is deprecated, please override options.mainFields instead
node-resolve: setting options.jsnext is deprecated, please override options.mainFields instead
node-resolve: setting options.main is deprecated, please override options.mainFields instead
[00:04:03:047] [watch] watch - bundling start
[00:04:08:487] [watch] watch - bundling crashed
{ code: 'FATAL',
  error: 
   { Error: [BABEL] /Users/agarciag/Documents/Apps/my-lib/src/index.ts: Invalid Option: module is not a valid top-level option.
        Maybe you meant to use 'modules'? (While processing: "/Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/preset-env/lib/index.js")
    at validateTopLevelOptions (/Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/preset-env/lib/normalize-options.js:61:13)
    at normalizeOptions (/Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/preset-env/lib/normalize-options.js:190:3)
    at _default (/Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/preset-env/lib/index.js:109:37)
    at /Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/core/lib/config/full.js:165:14)
    at cachedFunction (/Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPresetDescriptor (/Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/core/lib/config/full.js:235:63)
    at config.presets.reduce (/Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/core/lib/config/full.js:77:21)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/core/lib/config/full.js:74:38)
     [stack]: 'Error: [BABEL] /Users/agarciag/Documents/Apps/my-lib/src/index.ts: Invalid Option: module is not a valid top-level option.\n        Maybe you meant to use \'modules\'? (While processing: "/Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/preset-env/lib/index.js")\n    at validateTopLevelOptions (/Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/preset-env/lib/normalize-options.js:61:13)\n    at normalizeOptions (/Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/preset-env/lib/normalize-options.js:190:3)\n    at _default (/Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/preset-env/lib/index.js:109:37)\n    at /Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12\n    at loadDescriptor (/Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/core/lib/config/full.js:165:14)\n    at cachedFunction (/Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/core/lib/config/caching.js:33:19)\n    at loadPresetDescriptor (/Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/core/lib/config/full.js:235:63)\n    at config.presets.reduce (/Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/core/lib/config/full.js:77:21)\n    at Array.reduce (<anonymous>)\n    at recurseDescriptors (/Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/core/lib/config/full.js:74:38)',
     [message]: '[BABEL] /Users/agarciag/Documents/Apps/my-lib/src/index.ts: Invalid Option: module is not a valid top-level option.\n        Maybe you meant to use \'modules\'? (While processing: "/Users/agarciag/Documents/Apps/my-lib/node_modules/@babel/preset-env/lib/index.js")',
     code: 'PLUGIN_ERROR',
     plugin: 'babel',
     hook: 'transform',
     id: '/Users/agarciag/Documents/Apps/my-lib/src/index.ts' } }
```

Did I do something wrong?

**Comment by andresggarcia** [comment]
I think, it's because this line could have a typo:
https://github.com/yohangz/packer-cli/blob/master/resources/dynamic/.babelrc.hbs#L36

Instead of `module`, shouldn't it be `modules`? 
I'm not an expert on babel, though. But fixing that, it's not showing the error anymore. 

But... I still can't run the project. On `npm run watch`, it only shows: 

```batch
➣  my-lib ➜ npm run watch
> my-lib@1.0.0 watch /Users/agarciag/Documents/Apps/my-lib
> packer watch

node-resolve: setting options.module is deprecated, please override options.mainFields instead
node-resolve: setting options.jsnext is deprecated, please override options.mainFields instead
node-resolve: setting options.main is deprecated, please override options.mainFields instead
[00:27:40:091] [watch] watch - bundling start
[00:27:41:888] [watch] watch - bundling end
```

**Comment by yohangz** [comment]
@andresggarcia Thanks for pointing the babel config issue. I've fixed it and pushed a new release.

I believe it is working fine as you have generated a node library module. It will always compile the source and generate the distribution when you change the source. You have to run the dist manually to see the output. However, it will open up on browser with watch mode if you are building a browser compliant module. Let me know if you need further clarifications.
